name: Show Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Set up Java'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: EA
      - name: 'Run status program'
        run: java @status
      - name: 'Run smoke test'
        run: java @verify -va github/openjdk/jdk/test/jdk/jdk/nio/Basic.java
